/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

/**
 *
 * @author matheus
 */
public class GuiMenu extends javax.swing.JFrame {

    /**
     * Creates new form GuiMenu
     */
    public GuiMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuItemCadastro = new javax.swing.JMenu();
        jMenuItemMédico = new javax.swing.JMenuItem();
        jMenuItemPaciente = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuItemRegistro = new javax.swing.JMenu();
        jMenuItemMarcarConsulta = new javax.swing.JMenuItem();
        jMenuItemMarcarExame = new javax.swing.JMenuItem();
        jMenuItemPrescreverMed = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinica POO");

        jMenuItemCadastro.setText("Cadastro");
        jMenuItemCadastro.setName("jMenu"); // NOI18N

        jMenuItemMédico.setText("Medico");
        jMenuItemMédico.setName("jMenuItemMédico"); // NOI18N
        jMenuItemMédico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMédicoActionPerformed(evt);
            }
        });
        jMenuItemCadastro.add(jMenuItemMédico);

        jMenuItemPaciente.setText("Paciente");
        jMenuItemPaciente.setName("jMenuItemPaciente"); // NOI18N
        jMenuItemPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPacienteActionPerformed(evt);
            }
        });
        jMenuItemCadastro.add(jMenuItemPaciente);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.setName("jMenuItemSair"); // NOI18N
        jMenuItemCadastro.add(jMenuItemSair);

        jMenuBar1.add(jMenuItemCadastro);

        jMenuItemRegistro.setText("Registro");
        jMenuItemRegistro.setName("jMenuItemRegistro"); // NOI18N

        jMenuItemMarcarConsulta.setText("Marcar Consulta");
        jMenuItemMarcarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMarcarConsultaActionPerformed(evt);
            }
        });
        jMenuItemRegistro.add(jMenuItemMarcarConsulta);

        jMenuItemMarcarExame.setText("Marcar Exame");
        jMenuItemMarcarExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMarcarExameActionPerformed(evt);
            }
        });
        jMenuItemRegistro.add(jMenuItemMarcarExame);

        jMenuItemPrescreverMed.setText("Prescrever Medicação");
        jMenuItemPrescreverMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrescreverMedActionPerformed(evt);
            }
        });
        jMenuItemRegistro.add(jMenuItemPrescreverMed);

        jMenuBar1.add(jMenuItemRegistro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemMédicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMédicoActionPerformed
        // TODO add your handling code here:
        GuiCadastroMedico guiMedico = new GuiCadastroMedico();
        guiMedico.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        guiMedico.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemMédicoActionPerformed

    private void jMenuItemPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPacienteActionPerformed
        // TODO add your handling code here:
        GuiCadastroPaciente guiPaciente = new GuiCadastroPaciente();
        guiPaciente.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        guiPaciente.setVisible(true);
    }//GEN-LAST:event_jMenuItemPacienteActionPerformed

    private void jMenuItemMarcarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMarcarConsultaActionPerformed
        // TODO add your handling code here:
        GuiMarcarConsulta guiConsulta = new GuiMarcarConsulta();
        guiConsulta.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        guiConsulta.setVisible(true);
    }//GEN-LAST:event_jMenuItemMarcarConsultaActionPerformed

    private void jMenuItemPrescreverMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrescreverMedActionPerformed
        // TODO add your handling code here:
        GuiPrescreverMedicacao guiMedicacao = new GuiPrescreverMedicacao();
        guiMedicacao.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        guiMedicacao.setVisible(true);
    }//GEN-LAST:event_jMenuItemPrescreverMedActionPerformed

    private void jMenuItemMarcarExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMarcarExameActionPerformed
        // TODO add your handling code here:
        GuiMarcarExame guiExame = new GuiMarcarExame();
        guiExame.setVisible(true);
    }//GEN-LAST:event_jMenuItemMarcarExameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuItemCadastro;
    private javax.swing.JMenuItem jMenuItemMarcarConsulta;
    private javax.swing.JMenuItem jMenuItemMarcarExame;
    private javax.swing.JMenuItem jMenuItemMédico;
    private javax.swing.JMenuItem jMenuItemPaciente;
    private javax.swing.JMenuItem jMenuItemPrescreverMed;
    private javax.swing.JMenu jMenuItemRegistro;
    private javax.swing.JMenuItem jMenuItemSair;
    // End of variables declaration//GEN-END:variables
}
